---
# File: clean.yml
# Type: task
# Part: Docker

## Uninstall lxc-docker
- name: Docker | Remove legacy package
  apt: name=lxc-docker state=absent
- name: Docker | Remove legacy repository
  apt_repository: repo='deb https://get.docker.io/ubuntu docker main' state=absent
- name: Docker | Remove legacy ppa file
  file: path=/etc/apt/sources.list.d/get_docker_io_ubuntu.list state=absent
- name: Docker | Remove legacy ppa key
  apt_key: keyserver=keyserver.ubuntu.com id=A88D21E9 state=absent

## Uninstall docker-engine
- name: Docker | Remove legacy package
  apt: name=docker-engine state=absent
- name: Docker | Remove legacy repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_lsb.codename }} main' state=absent
  # file: path=/etc/apt/sources.list.d/apt_dockerproject_org_repo.list state=absent
- name: Docker | Remove legacy ppa key
  apt_key: keyserver=keyserver.ubuntu.com id=2C52609D state=absent
