---
# File: configure-systemd.yml
# Type: task
# Part: Docker

# legacy upstart config
- name: Docker | Remove upstart service configuration
  file: path=/etc/init/docker.conf state=absent
  notify: restart docker

# docker.socket
- name: Docker | Deploy systemd docker.socket configuration
  template: src=lib_systemd_system_docker.socket.j2 dest=/lib/systemd/system/docker.socket owner=root group=root mode=0644
  notify: restart docker
- name: Docker | Link systemd docker.socket configuration
  file: state=link src=/lib/systemd/system/docker.socket dest=/etc/systemd/system/sockets.target.wants/docker.socket
  notify: restart docker

# docker.service
- name: Docker | Deploy systemd docker.socket configuration
  template: src=lib_systemd_system_docker.service.j2 dest=/lib/systemd/system/docker.service owner=root group=root mode=0644
  notify: restart docker
- name: Docker | Link systemd docker.socket configuration
  file: state=link src=/lib/systemd/system/docker.service dest=/etc/systemd/system/multi-user.target.wants/docker.service
  notify: restart docker
