---
# File: main.yml
# Type: task
# Part: Docker

## Kernel upgrade for 12.04
- name: Docker | Upgrade 12.04 kernel
  apt: name={{ item }} state=latest
  with_items:
    - linux-image-generic-lts-trusty
    - linux-headers-generic-lts-trusty
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '12.04'
  register: kernel_updated
- name: Docker | Reboot
  command: reboot
  when: kernel_updated | changed
- name: Docker | Wait for SSH
  local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} delay=30 timeout=900 state=started
  when: kernel_updated | changed

## Kernel upgrade for 14.04
- name: Docker | Install recommended packages
  apt: name={{ item }} state=latest
  with_items:
    - linux-image-extra-{{ ansible_kernel }}
    - linux-image-extra-virtual
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

## Install docker-ce
- name: Docker | Install ppa key
  apt_key: keyserver=keyserver.ubuntu.com id=0EBFCD88
- name: Docker | Install repository
  apt_repository: repo='deb [arch={{ docker_apt_architecture }}] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable' state=present
- name: Docker | Install package
  apt: name=docker-ce state={{ docker_apt_state }}
