---
# File: main.yml
# Type: task
# Part: Docker

- name: Docker | Check Ubuntu release
  fail: msg="Docker only support Ubuntu from {{ ansible_distribution_version }}"
  when: ansible_distribution != 'Ubuntu' or ansible_lsb.major_release|int < 12
- name: Docker | Check architecture
  fail: msg="Docker only support x86_64 architecture"
  when: ansible_architecture != 'x86_64'
- name: Facts | Set docker_apt_architecture
  set_fact: docker_apt_architecture=amd64
  when: ansible_architecture == 'x86_64'

## Install
- name: Docker | Clean legacy install
  include: clean.yml
  when: docker_clean_legacy|bool

## Install
- name: Docker | Install
  include: install.yml

## Configure
- name: Docker | Configure
  tags: system_docker_configure
  include: configure.yml

## Configure service
- include: configure-systemd.yml
  when: not docker and ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 16
- include: configure-upstart.yml
  when: not docker and ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int <= 14

## DockerCompose
- name: Docker | Install DockerCompose
  tags: system_docker-compose
  include: docker-compose.yml
  when: docker_compose_install

## DockerGen
- name: Docker | Install DockerGen
  tags: system_docker-gen
  include: docker-gen.yml
  when: docker_gen_install

## Check service
- name: Docker | Check service daemon
  service: name=docker state=started
